name: gh-deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_GHTOKEN: ${{ secrets.ACCESS_TOKEN }}
          envkey_GCAUTH: ${{ secrets.GOOGLEAPIKEY }}
      - 
        name: Setup-node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      -
        name: Fetch Data
        run: |
          npm i axios
          npm run fetch
      -
        name: Build project
        run : npm run build
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: release
#           cname: upvision.co
      
